'use client';
import Head from 'next/head';
import { useContext } from 'react';
import ReactLoading from 'react-loading';

import ProductCard from 'components/ProductCard';
import { ProductType } from 'components/ProductCard';
import SearchForm from 'components/SearchForm';

import { Context } from 'context/Context';

export default function Home() {
  const { scrapingData, isLoading } = useContext(Context);
  const { products } = scrapingData;
  return (
    <>
      <Head>
        <title>Ecommerce Webscraping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchForm />
      <div className="flex w-full justify-center p-8 gap-24">
        {isLoading ? (
          <ReactLoading
            type="spin"
            color="dark"
            height={40}
            width={40}
            className="flex justify-center"
          />
        ) : (
          products?.map((product: ProductType) => (
            <ProductCard
              key={product.title}
              category={product.category}
              picture={product.picture}
              title={product.title}
              price={product.price}
              link={product.link}
            />
          ))
        )}
      </div>
    </>
  );
}
