'use client';
import Head from 'next/head';

import SearchForm from '@/components/SearchForm';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce Webscraping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchForm />
    </>
  );
}
