'use client';
import Head from 'next/head';
import { useContext } from 'react';

import ProductCard from 'components/ProductCard';
import SearchForm from 'components/SearchForm';

import { Context } from 'context/Context';

export default function Home() {
  const { scrapingData } = useContext(Context);
  const { products } = scrapingData;
  return (
    <>
      <Head>
        <title>Ecommerce Webscraping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchForm />
      <div className="flex w-full justify-between p-8">
        {products?.map((product) => (
          <ProductCard
            key={product.title}
            category={product.category}
            picture={product.picture}
            title={product.title}
            price={product.price}
            link={product.link}
          />
        ))}
      </div>
    </>
  );
}
